# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-BitTorrent-LibBT-Tracker
version:      0.016
version_from: lib/Net/BitTorrent/LibBT/Tracker.pm
installdirs:  site
requires:
    APR:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
